title: <p align="center"> Tanaya Jadhav </p>
logo: /assets/img/Profile.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/tanaya-jadhav-812646191/">LinkedIn</a> |
  <a href="https://github.com/tanaya1708">GitHub</a>
  </p>
  
  <p align="left">
  I'm working as a Software Engineer for Capgemini </br>
  Full stack Java Developer | Reactjs </br>
  </p>
  </br>
theme: jekyll-theme-minimal
